require("dotenv").config();
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const User = require('../models/User');
const Claim = require('../models/Claim');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/healthcare_claims';

const users = [
  {
    name: 'Dr. Sarah Mitchell',
    email: 'admin@claimsdash.com',
    password: 'Admin@1234',
    role: 'admin',
    department: 'Administration',
  },
  {
    name: 'James Okafor',
    email: 'james@claimsdash.com',
    password: 'Staff@1234',
    role: 'staff',
    department: 'Billing',
  },
  {
    name: 'Priya Sharma',
    email: 'priya@claimsdash.com',
    password: 'Staff@1234',
    role: 'staff',
    department: 'Billing',
  },
  {
    name: 'Carlos Rivera',
    email: 'carlos@claimsdash.com',
    password: 'Staff@1234',
    role: 'staff',
    department: 'Claims Processing',
  },
];

const claimTemplates = (userIds) => [
  {
    claimId: 'CLM-2024-0001',
    patientName: 'Margaret Thompson',
    patientDOB: '1958-04-12',
    procedure: 'Cardiac Catheterization',
    procedureCode: '93510',
    diagnosisCode: 'I25.10',
    amount: 4850.0,
    status: 'Approved',
    date: new Date('2024-11-01'),
    insurance: 'BlueCross BlueShield',
    insurancePolicyNumber: 'BCB-998821',
    rejectionReason: null,
    assignedTo: userIds[1],
    priority: 'High',
  },
  {
    claimId: 'CLM-2024-0002',
    patientName: 'Robert Hayes',
    patientDOB: '1971-08-22',
    procedure: 'MRI Brain (without contrast)',
    procedureCode: '70553',
    diagnosisCode: 'G43.909',
    amount: 1200.0,
    status: 'Rejected',
    date: new Date('2024-11-03'),
    insurance: 'Aetna',
    insurancePolicyNumber: 'AET-445632',
    rejectionReason: 'Prior Authorization Required',
    assignedTo: userIds[2],
    priority: 'High',
    resubmissionCount: 0,
  },
  {
    claimId: 'CLM-2024-0003',
    patientName: 'Linda Nguyen',
    patientDOB: '1983-02-14',
    procedure: 'Colonoscopy with Biopsy',
    procedureCode: '45380',
    diagnosisCode: 'K57.30',
    amount: 875.5,
    status: 'Pending',
    date: new Date('2024-11-05'),
    insurance: 'UnitedHealthcare',
    insurancePolicyNumber: 'UHC-771234',
    rejectionReason: null,
    assignedTo: userIds[3],
    priority: 'Medium',
  },
  {
    claimId: 'CLM-2024-0004',
    patientName: 'David Patel',
    patientDOB: '1945-11-30',
    procedure: 'Total Knee Replacement',
    procedureCode: '27447',
    diagnosisCode: 'M17.11',
    amount: 28500.0,
    status: 'Approved',
    date: new Date('2024-11-06'),
    insurance: 'Medicare',
    insurancePolicyNumber: 'MCR-1A2B3C',
    rejectionReason: null,
    assignedTo: userIds[1],
    priority: 'High',
  },
  {
    claimId: 'CLM-2024-0005',
    patientName: 'Susan Carter',
    patientDOB: '1967-06-19',
    procedure: 'Hysterectomy (Laparoscopic)',
    procedureCode: '58550',
    diagnosisCode: 'D25.9',
    amount: 9200.0,
    status: 'Rejected',
    date: new Date('2024-11-07'),
    insurance: 'Cigna',
    insurancePolicyNumber: 'CIG-334421',
    rejectionReason: 'Duplicate Claim Submission',
    assignedTo: userIds[2],
    priority: 'High',
    resubmissionCount: 1,
  },
  {
    claimId: 'CLM-2024-0006',
    patientName: 'Michael Torres',
    patientDOB: '1990-03-05',
    procedure: 'Appendectomy (Laparoscopic)',
    procedureCode: '44950',
    diagnosisCode: 'K35.80',
    amount: 6400.0,
    status: 'Approved',
    date: new Date('2024-11-08'),
    insurance: 'BlueCross BlueShield',
    insurancePolicyNumber: 'BCB-112234',
    rejectionReason: null,
    assignedTo: userIds[3],
    priority: 'High',
  },
  {
    claimId: 'CLM-2024-0007',
    patientName: 'Angela Brooks',
    patientDOB: '1978-09-27',
    procedure: 'Mammography (Bilateral)',
    procedureCode: '77067',
    diagnosisCode: 'Z12.31',
    amount: 320.0,
    status: 'Rejected',
    date: new Date('2024-11-10'),
    insurance: 'Humana',
    insurancePolicyNumber: 'HUM-556677',
    rejectionReason: 'Patient Not Covered on Date of Service',
    assignedTo: userIds[1],
    priority: 'Low',
  },
  {
    claimId: 'CLM-2024-0008',
    patientName: 'James Wilson',
    patientDOB: '1953-12-03',
    procedure: 'Coronary Artery Bypass Graft (CABG)',
    procedureCode: '33533',
    diagnosisCode: 'I25.110',
    amount: 65000.0,
    status: 'Pending',
    date: new Date('2024-11-12'),
    insurance: 'Medicare',
    insurancePolicyNumber: 'MCR-4D5E6F',
    rejectionReason: null,
    assignedTo: userIds[2],
    priority: 'High',
  },
  {
    claimId: 'CLM-2024-0009',
    patientName: 'Patricia Kim',
    patientDOB: '1988-07-14',
    procedure: 'Thyroidectomy (Total)',
    procedureCode: '60240',
    diagnosisCode: 'C73',
    amount: 11800.0,
    status: 'Approved',
    date: new Date('2024-11-13'),
    insurance: 'Aetna',
    insurancePolicyNumber: 'AET-889900',
    rejectionReason: null,
    assignedTo: userIds[3],
    priority: 'High',
  },
  {
    claimId: 'CLM-2024-0010',
    patientName: 'Richard Johnson',
    patientDOB: '1962-01-28',
    procedure: 'Lumbar Spinal Fusion',
    procedureCode: '22612',
    diagnosisCode: 'M48.06',
    amount: 42000.0,
    status: 'Rejected',
    date: new Date('2024-11-14'),
    insurance: 'UnitedHealthcare',
    insurancePolicyNumber: 'UHC-998877',
    rejectionReason: 'Prior Authorization Required',
    assignedTo: userIds[1],
    priority: 'High',
  },
  {
    claimId: 'CLM-2024-0011',
    patientName: 'Helen Garcia',
    patientDOB: '1975-05-09',
    procedure: 'Cataract Surgery with IOL Implant',
    procedureCode: '66984',
    diagnosisCode: 'H26.9',
    amount: 3100.0,
    status: 'Approved',
    date: new Date('2024-11-15'),
    insurance: 'Cigna',
    insurancePolicyNumber: 'CIG-667788',
    rejectionReason: null,
    assignedTo: userIds[2],
    priority: 'Medium',
  },
  {
    claimId: 'CLM-2024-0012',
    patientName: 'Thomas Anderson',
    patientDOB: '1948-11-16',
    procedure: 'Hip Replacement (Total)',
    procedureCode: '27130',
    diagnosisCode: 'M16.11',
    amount: 31500.0,
    status: 'Pending',
    date: new Date('2024-11-16'),
    insurance: 'Medicare',
    insurancePolicyNumber: 'MCR-7G8H9I',
    rejectionReason: null,
    assignedTo: userIds[3],
    priority: 'High',
  },
  {
    claimId: 'CLM-2024-0013',
    patientName: 'Jennifer Lee',
    patientDOB: '1993-04-22',
    procedure: 'Gallbladder Removal (Laparoscopic)',
    procedureCode: '47562',
    diagnosisCode: 'K80.20',
    amount: 7800.0,
    status: 'Rejected',
    date: new Date('2024-11-18'),
    insurance: 'BlueCross BlueShield',
    insurancePolicyNumber: 'BCB-334455',
    rejectionReason: 'Incorrect Procedure Code',
    assignedTo: userIds[1],
    priority: 'Medium',
  },
  {
    claimId: 'CLM-2024-0014',
    patientName: 'Charles Martinez',
    patientDOB: '1966-08-11',
    procedure: 'Prostate Biopsy (Transrectal)',
    procedureCode: '55700',
    diagnosisCode: 'N40.1',
    amount: 1850.0,
    status: 'Approved',
    date: new Date('2024-11-19'),
    insurance: 'Humana',
    insurancePolicyNumber: 'HUM-223344',
    rejectionReason: null,
    assignedTo: userIds[2],
    priority: 'Medium',
  },
  {
    claimId: 'CLM-2024-0015',
    patientName: 'Barbara Wilson',
    patientDOB: '1970-03-15',
    procedure: 'Breast Reconstruction (Post-mastectomy)',
    procedureCode: '19357',
    diagnosisCode: 'C50.912',
    amount: 18400.0,
    status: 'Pending',
    date: new Date('2024-11-20'),
    insurance: 'UnitedHealthcare',
    insurancePolicyNumber: 'UHC-556655',
    rejectionReason: null,
    assignedTo: userIds[3],
    priority: 'High',
  },
  {
    claimId: 'CLM-2024-0016',
    patientName: 'Kevin Brown',
    patientDOB: '1985-10-07',
    procedure: 'Carpal Tunnel Release',
    procedureCode: '64721',
    diagnosisCode: 'G56.01',
    amount: 2200.0,
    status: 'Rejected',
    date: new Date('2024-11-21'),
    insurance: 'Aetna',
    insurancePolicyNumber: 'AET-112211',
    rejectionReason: 'Insufficient Medical Necessity Documentation',
    assignedTo: userIds[1],
    priority: 'Low',
  },
  {
    claimId: 'CLM-2024-0017',
    patientName: 'Dorothy Evans',
    patientDOB: '1955-06-30',
    procedure: 'Knee Arthroscopy with Meniscectomy',
    procedureCode: '29881',
    diagnosisCode: 'M23.200',
    amount: 5600.0,
    status: 'Approved',
    date: new Date('2024-11-22'),
    insurance: 'Medicare',
    insurancePolicyNumber: 'MCR-2J3K4L',
    rejectionReason: null,
    assignedTo: userIds[2],
    priority: 'Medium',
  },
  {
    claimId: 'CLM-2024-0018',
    patientName: 'Steven Davis',
    patientDOB: '1979-02-18',
    procedure: 'Hernia Repair (Inguinal)',
    procedureCode: '49505',
    diagnosisCode: 'K40.90',
    amount: 4300.0,
    status: 'Pending',
    date: new Date('2024-11-23'),
    insurance: 'Cigna',
    insurancePolicyNumber: 'CIG-889922',
    rejectionReason: null,
    assignedTo: userIds[3],
    priority: 'Medium',
  },
  {
    claimId: 'CLM-2024-0019',
    patientName: 'Nancy Robinson',
    patientDOB: '1961-09-04',
    procedure: 'Mastectomy (Modified Radical)',
    procedureCode: '19307',
    diagnosisCode: 'C50.911',
    amount: 14200.0,
    status: 'Rejected',
    date: new Date('2024-11-24'),
    insurance: 'BlueCross BlueShield',
    insurancePolicyNumber: 'BCB-778899',
    rejectionReason: 'Prior Authorization Required',
    assignedTo: userIds[1],
    priority: 'High',
  },
  {
    claimId: 'CLM-2024-0020',
    patientName: 'Paul Jackson',
    patientDOB: '1938-07-21',
    procedure: 'Pacemaker Implantation (Dual Chamber)',
    procedureCode: '33208',
    diagnosisCode: 'I44.30',
    amount: 22000.0,
    status: 'Approved',
    date: new Date('2024-11-25'),
    insurance: 'Medicare',
    insurancePolicyNumber: 'MCR-5M6N7O',
    rejectionReason: null,
    assignedTo: userIds[2],
    priority: 'High',
  },
];

const seedDatabase = async () => {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('✅ Connected to MongoDB');

    // Clear existing data
    await User.deleteMany({});
    await Claim.deleteMany({});
    console.log('🗑️  Cleared existing data');

    // Seed users
    const createdUsers = await User.create(users);
    console.log(`👥 Created ${createdUsers.length} users`);

    const userIds = createdUsers.map((u) => u._id);

    // Seed claims
    const claimsData = claimTemplates(userIds);
    const createdClaims = await Claim.create(claimsData);
    console.log(`📋 Created ${createdClaims.length} claims`);

    console.log('\n🎉 Database seeded successfully!');
    console.log('\nLogin credentials:');
    console.log('─────────────────────────────────────────');
    console.log('Admin:  admin@claimsdash.com  | Admin@1234');
    console.log('Staff:  james@claimsdash.com  | Staff@1234');
    console.log('Staff:  priya@claimsdash.com  | Staff@1234');
    console.log('Staff:  carlos@claimsdash.com | Staff@1234');
    console.log('─────────────────────────────────────────');

    process.exit(0);
  } catch (err) {
    console.error('❌ Seeder error:', err.message);
    process.exit(1);
  }
};

seedDatabase();